name: Publish

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: The type of release
        required: true
        type: choice
        options: ["release", "beta", "alpha"]
      minecraft-versions:
        description: Overrides for supported versions
        required: false
        type: string

jobs:
  publish:
    uses: MattiDragon/MattiDragon/.github/workflows/publish-mc-mod.yaml@00051ad2ae1350c882ab08a382d4dda38eff121b
    with:
      version-type: ${{ inputs.version-type }}
      minecraft-versions: ${{ inputs.minecraft-versions }}
      java-version: 21
      modrinth-id: cjSHexOj
      curseforge-id: 1050872
    secrets:
      modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
      curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
